
export const mockWeather = {
    latitude: 52.3667,
    longitude: 4.8945,
    timezone: 'Europe/Amsterdam',
    currently: {
        time: 1574102877,
        summary: 'Possible Drizzle',
        icon: 'rain',
        precipIntensity: 0.1041,
        precipProbability: 0.43,
        precipType: 'rain',
        temperature: 7.62,
        apparentTemperature: 3.64,
        dewPoint: 5.68,
        humidity: 0.88,
        pressure: 1008.7,
        windSpeed: 7.8,
        windGust: 12.37,
        windBearing: 326,
        cloudCover: 0.67,
        uvIndex: 0,
        visibility: 10.681,
        ozone: 326.6
    },
    hourly: {
        summary: 'Possible light rain until tomorrow morning.',
        icon: 'rain',
        data: [
            {
                time: 1574100000,
                summary: 'Possible Drizzle',
                icon: 'rain',
                precipIntensity: 0.1345,
                precipProbability: 0.48,
                precipType: 'rain',
                temperature: 7.67,
                apparentTemperature: 3.75,
                dewPoint: 5.7,
                humidity: 0.87,
                pressure: 1008.5,
                windSpeed: 7.65,
                windGust: 12.5,
                windBearing: 327,
                cloudCover: 0.67,
                uvIndex: 0,
                visibility: 10.758,
                ozone: 325.7
            },
            {
                time: 1574103600,
                summary: 'Possible Drizzle',
                icon: 'rain',
                precipIntensity: 0.0983,
                precipProbability: 0.41,
                precipType: 'rain',
                temperature: 7.61,
                apparentTemperature: 3.65,
                dewPoint: 5.69,
                humidity: 0.88,
                pressure: 1008.8,
                windSpeed: 7.72,
                windGust: 12.27,
                windBearing: 325,
                cloudCover: 0.67,
                uvIndex: 0,
                visibility: 10.771,
                ozone: 326.9
            },
            {
                time: 1574107200,
                summary: 'Mostly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0956,
                precipProbability: 0.37,
                precipType: 'rain',
                temperature: 7.58,
                apparentTemperature: 3.77,
                dewPoint: 5.63,
                humidity: 0.87,
                pressure: 1009.2,
                windSpeed: 7.19,
                windGust: 11.4,
                windBearing: 320,
                cloudCover: 0.71,
                uvIndex: 0,
                visibility: 12.181,
                ozone: 328.4
            },
            {
                time: 1574110800,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.1229,
                precipProbability: 0.22,
                precipType: 'rain',
                temperature: 8.05,
                apparentTemperature: 4.75,
                dewPoint: 5.51,
                humidity: 0.84,
                pressure: 1009.6,
                windSpeed: 6.03,
                windGust: 10.77,
                windBearing: 321,
                cloudCover: 0.89,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 330.1
            },
            {
                time: 1574114400,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.0627,
                precipProbability: 0.18,
                precipType: 'rain',
                temperature: 7.67,
                apparentTemperature: 4.27,
                dewPoint: 5.91,
                humidity: 0.89,
                pressure: 1010,
                windSpeed: 6.05,
                windGust: 10.79,
                windBearing: 319,
                cloudCover: 0.94,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 332.1
            },
            {
                time: 1574118000,
                summary: 'Mostly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0213,
                precipProbability: 0.09,
                precipType: 'rain',
                temperature: 7.19,
                apparentTemperature: 3.75,
                dewPoint: 5.62,
                humidity: 0.9,
                pressure: 1010.4,
                windSpeed: 5.82,
                windGust: 11.06,
                windBearing: 314,
                cloudCover: 0.86,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 334.4
            },
            {
                time: 1574121600,
                summary: 'Mostly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.036,
                precipProbability: 0.11,
                precipType: 'rain',
                temperature: 6.77,
                apparentTemperature: 3.24,
                dewPoint: 5.47,
                humidity: 0.91,
                pressure: 1010.9,
                windSpeed: 5.74,
                windGust: 11.21,
                windBearing: 310,
                cloudCover: 0.8,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 335.8
            },
            {
                time: 1574125200,
                summary: 'Mostly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.1406,
                precipProbability: 0.33,
                precipType: 'rain',
                temperature: 6.42,
                apparentTemperature: 2.67,
                dewPoint: 5.59,
                humidity: 0.94,
                pressure: 1011.2,
                windSpeed: 6.07,
                windGust: 11.16,
                windBearing: 307,
                cloudCover: 0.77,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 336.3
            },
            {
                time: 1574128800,
                summary: 'Possible Light Rain',
                icon: 'rain',
                precipIntensity: 0.5535,
                precipProbability: 0.49,
                precipType: 'rain',
                temperature: 6.15,
                apparentTemperature: 2.26,
                dewPoint: 5.39,
                humidity: 0.95,
                pressure: 1011.4,
                windSpeed: 6.25,
                windGust: 11,
                windBearing: 305,
                cloudCover: 0.75,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 336
            },
            {
                time: 1574132400,
                summary: 'Possible Light Rain',
                icon: 'rain',
                precipIntensity: 0.9492,
                precipProbability: 0.47,
                precipType: 'rain',
                temperature: 6.01,
                apparentTemperature: 2.11,
                dewPoint: 5.3,
                humidity: 0.95,
                pressure: 1011.8,
                windSpeed: 6.19,
                windGust: 10.57,
                windBearing: 305,
                cloudCover: 0.75,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 334.8
            },
            {
                time: 1574136000,
                summary: 'Possible Light Rain',
                icon: 'rain',
                precipIntensity: 0.7953,
                precipProbability: 0.51,
                precipType: 'rain',
                temperature: 5.99,
                apparentTemperature: 2.27,
                dewPoint: 5.46,
                humidity: 0.96,
                pressure: 1012.3,
                windSpeed: 5.69,
                windGust: 9.68,
                windBearing: 308,
                cloudCover: 0.78,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 332.7
            },
            {
                time: 1574139600,
                summary: 'Possible Light Rain',
                icon: 'rain',
                precipIntensity: 0.461,
                precipProbability: 0.42,
                precipType: 'rain',
                temperature: 6.14,
                apparentTemperature: 2.85,
                dewPoint: 5.74,
                humidity: 0.97,
                pressure: 1012.8,
                windSpeed: 4.81,
                windGust: 8.53,
                windBearing: 314,
                cloudCover: 0.82,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 329.7
            },
            {
                time: 1574143200,
                summary: 'Mostly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.2781,
                precipProbability: 0.3,
                precipType: 'rain',
                temperature: 6.3,
                apparentTemperature: 3.43,
                dewPoint: 6.15,
                humidity: 0.99,
                pressure: 1013.3,
                windSpeed: 4.04,
                windGust: 7.58,
                windBearing: 319,
                cloudCover: 0.86,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 326.2
            },
            {
                time: 1574146800,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.2019,
                precipProbability: 0.27,
                precipType: 'rain',
                temperature: 6.2,
                apparentTemperature: 3.6,
                dewPoint: 6.2,
                humidity: 1,
                pressure: 1013.9,
                windSpeed: 3.55,
                windGust: 7.08,
                windBearing: 323,
                cloudCover: 0.9,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 321.5
            },
            {
                time: 1574150400,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.1636,
                precipProbability: 0.24,
                precipType: 'rain',
                temperature: 6.12,
                apparentTemperature: 3.71,
                dewPoint: 6.12,
                humidity: 1,
                pressure: 1014.4,
                windSpeed: 3.2,
                windGust: 6.78,
                windBearing: 325,
                cloudCover: 0.94,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 316.2
            },
            {
                time: 1574154000,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.1409,
                precipProbability: 0.23,
                precipType: 'rain',
                temperature: 6.33,
                apparentTemperature: 4.19,
                dewPoint: 6.31,
                humidity: 1,
                pressure: 1015,
                windSpeed: 2.89,
                windGust: 6.43,
                windBearing: 323,
                cloudCover: 0.96,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 312.1
            },
            {
                time: 1574157600,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.0956,
                precipProbability: 0.17,
                precipType: 'rain',
                temperature: 7.11,
                apparentTemperature: 5.31,
                dewPoint: 6.56,
                humidity: 0.96,
                pressure: 1015.5,
                windSpeed: 2.61,
                windGust: 5.89,
                windBearing: 314,
                cloudCover: 0.96,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 310.4
            },
            {
                time: 1574161200,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.0591,
                precipProbability: 0.12,
                precipType: 'rain',
                temperature: 8.05,
                apparentTemperature: 6.54,
                dewPoint: 6.44,
                humidity: 0.9,
                pressure: 1015.9,
                windSpeed: 2.47,
                windGust: 5.3,
                windBearing: 305,
                cloudCover: 0.95,
                uvIndex: 1,
                visibility: 16.093,
                ozone: 309.9
            },
            {
                time: 1574164800,
                summary: 'Overcast',
                icon: 'cloudy',
                precipIntensity: 0.0433,
                precipProbability: 0.11,
                precipType: 'rain',
                temperature: 8.51,
                apparentTemperature: 7.18,
                dewPoint: 6.17,
                humidity: 0.85,
                pressure: 1016.1,
                windSpeed: 2.33,
                windGust: 4.66,
                windBearing: 301,
                cloudCover: 0.9,
                uvIndex: 1,
                visibility: 16.093,
                ozone: 309.1
            },
            {
                time: 1574168400,
                summary: 'Mostly Cloudy',
                icon: 'partly-cloudy-day',
                precipIntensity: 0.0247,
                precipProbability: 0.09,
                precipType: 'rain',
                temperature: 8.37,
                apparentTemperature: 7.19,
                dewPoint: 5.95,
                humidity: 0.85,
                pressure: 1016.3,
                windSpeed: 2.12,
                windGust: 3.94,
                windBearing: 305,
                cloudCover: 0.77,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 307.5
            },
            {
                time: 1574172000,
                summary: 'Mostly Cloudy',
                icon: 'partly-cloudy-day',
                precipIntensity: 0.0103,
                precipProbability: 0.06,
                precipType: 'rain',
                temperature: 7.92,
                apparentTemperature: 6.87,
                dewPoint: 5.59,
                humidity: 0.85,
                pressure: 1016.3,
                windSpeed: 1.89,
                windGust: 3.17,
                windBearing: 271,
                cloudCover: 0.61,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 305.6
            },
            {
                time: 1574175600,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-day',
                precipIntensity: 0.0079,
                precipProbability: 0.04,
                precipType: 'rain',
                temperature: 7.3,
                apparentTemperature: 6.36,
                dewPoint: 5.05,
                humidity: 0.86,
                pressure: 1016.6,
                windSpeed: 1.68,
                windGust: 2.54,
                windBearing: 282,
                cloudCover: 0.49,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 303.4
            },
            {
                time: 1574179200,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0167,
                precipProbability: 0.06,
                precipType: 'rain',
                temperature: 6.48,
                apparentTemperature: 5.68,
                dewPoint: 4.21,
                humidity: 0.85,
                pressure: 1016.9,
                windSpeed: 1.47,
                windGust: 2.11,
                windBearing: 292,
                cloudCover: 0.48,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 300.4
            },
            {
                time: 1574182800,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0498,
                precipProbability: 0.11,
                precipType: 'rain',
                temperature: 5.57,
                apparentTemperature: 5.57,
                dewPoint: 3.61,
                humidity: 0.87,
                pressure: 1017.3,
                windSpeed: 1.26,
                windGust: 1.83,
                windBearing: 253,
                cloudCover: 0.52,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 297
            },
            {
                time: 1574186400,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0757,
                precipProbability: 0.12,
                precipType: 'rain',
                temperature: 4.84,
                apparentTemperature: 4.84,
                dewPoint: 3.35,
                humidity: 0.9,
                pressure: 1017.7,
                windSpeed: 1.11,
                windGust: 1.65,
                windBearing: 276,
                cloudCover: 0.52,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 294
            },
            {
                time: 1574190000,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0488,
                precipProbability: 0.09,
                precipType: 'rain',
                temperature: 4.38,
                apparentTemperature: 4.38,
                dewPoint: 3.13,
                humidity: 0.92,
                pressure: 1017.9,
                windSpeed: 1.09,
                windGust: 1.63,
                windBearing: 322,
                cloudCover: 0.43,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 291.9
            },
            {
                time: 1574193600,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0.0139,
                precipProbability: 0.03,
                precipType: 'rain',
                temperature: 4.13,
                apparentTemperature: 4.13,
                dewPoint: 3.13,
                humidity: 0.93,
                pressure: 1018.2,
                windSpeed: 1.13,
                windGust: 1.71,
                windBearing: 140,
                cloudCover: 0.29,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 290.2
            },
            {
                time: 1574197200,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 3.82,
                apparentTemperature: 3.82,
                dewPoint: 3.13,
                humidity: 0.95,
                pressure: 1018.3,
                windSpeed: 1.17,
                windGust: 1.78,
                windBearing: 178,
                cloudCover: 0.2,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 288.6
            },
            {
                time: 1574200800,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 2.94,
                apparentTemperature: 2.94,
                dewPoint: 2.56,
                humidity: 0.97,
                pressure: 1017.6,
                windSpeed: 1.15,
                windGust: 1.77,
                windBearing: 159,
                cloudCover: 0.17,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 287.1
            },
            {
                time: 1574204400,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 2.42,
                apparentTemperature: 2.42,
                dewPoint: 2.27,
                humidity: 0.99,
                pressure: 1017.6,
                windSpeed: 1.2,
                windGust: 1.75,
                windBearing: 159,
                cloudCover: 0.17,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 285.8
            },
            {
                time: 1574208000,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 2.68,
                apparentTemperature: 2.68,
                dewPoint: 2.68,
                humidity: 1,
                pressure: 1018.5,
                windSpeed: 1.1,
                windGust: 1.77,
                windBearing: 167,
                cloudCover: 0.18,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 284.4
            },
            {
                time: 1574211600,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 1.49,
                apparentTemperature: 0.07,
                dewPoint: 1.49,
                humidity: 1,
                pressure: 1017.9,
                windSpeed: 1.41,
                windGust: 1.89,
                windBearing: 155,
                cloudCover: 0.21,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 282.9
            },
            {
                time: 1574215200,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 1.11,
                apparentTemperature: -0.63,
                dewPoint: 1.11,
                humidity: 1,
                pressure: 1017.9,
                windSpeed: 1.6,
                windGust: 2.06,
                windBearing: 149,
                cloudCover: 0.25,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 281.2
            },
            {
                time: 1574218800,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0.0061,
                precipProbability: 0.02,
                precipType: 'rain',
                temperature: 1.31,
                apparentTemperature: -0.87,
                dewPoint: 1.31,
                humidity: 1,
                pressure: 1018.3,
                windSpeed: 1.96,
                windGust: 2.24,
                windBearing: 146,
                cloudCover: 0.3,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 279.5
            },
            {
                time: 1574222400,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0066,
                precipProbability: 0.02,
                precipType: 'snow',
                precipAccumulation: 0.0041,
                temperature: 0.55,
                apparentTemperature: -1.69,
                dewPoint: 0.55,
                humidity: 1,
                pressure: 1017.6,
                windSpeed: 1.9,
                windGust: 2.32,
                windBearing: 141,
                cloudCover: 0.38,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 277.6
            },
            {
                time: 1574226000,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0052,
                precipProbability: 0.03,
                precipType: 'snow',
                precipAccumulation: 0.0036,
                temperature: 0.44,
                apparentTemperature: -1.98,
                dewPoint: 0.44,
                humidity: 1,
                pressure: 1017.4,
                windSpeed: 2.02,
                windGust: 2.44,
                windBearing: 141,
                cloudCover: 0.46,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 275.7
            },
            {
                time: 1574229600,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0128,
                precipProbability: 0.03,
                precipType: 'snow',
                precipAccumulation: 0.0071,
                temperature: 0.85,
                apparentTemperature: -1.6,
                dewPoint: 0.85,
                humidity: 1,
                pressure: 1018,
                windSpeed: 2.11,
                windGust: 2.56,
                windBearing: 144,
                cloudCover: 0.48,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 274.1
            },
            {
                time: 1574233200,
                summary: 'Partly Cloudy',
                icon: 'partly-cloudy-night',
                precipIntensity: 0.0096,
                precipProbability: 0.04,
                precipType: 'snow',
                precipAccumulation: 0.0053,
                temperature: 0.8,
                apparentTemperature: -1.8,
                dewPoint: 0.8,
                humidity: 1,
                pressure: 1017.4,
                windSpeed: 2.23,
                windGust: 2.67,
                windBearing: 135,
                cloudCover: 0.35,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 273
            },
            {
                time: 1574236800,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0.017,
                precipProbability: 0.04,
                precipType: 'rain',
                temperature: 1.35,
                apparentTemperature: -1.24,
                dewPoint: 1.35,
                humidity: 1,
                pressure: 1017.6,
                windSpeed: 2.33,
                windGust: 2.85,
                windBearing: 129,
                cloudCover: 0.15,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 272.3
            },
            {
                time: 1574240400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0.0068,
                precipProbability: 0.03,
                precipType: 'rain',
                temperature: 2,
                apparentTemperature: -0.76,
                dewPoint: 2,
                humidity: 1,
                pressure: 1017.8,
                windSpeed: 2.61,
                windGust: 3.12,
                windBearing: 123,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 271.7
            },
            {
                time: 1574244000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0.0105,
                precipProbability: 0.05,
                precipType: 'rain',
                temperature: 3.15,
                apparentTemperature: 0.71,
                dewPoint: 3.15,
                humidity: 1,
                pressure: 1017.2,
                windSpeed: 2.5,
                windGust: 3.62,
                windBearing: 122,
                cloudCover: 0,
                uvIndex: 1,
                visibility: 16.093,
                ozone: 271.1
            },
            {
                time: 1574247600,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 4.41,
                apparentTemperature: 2.12,
                dewPoint: 4.19,
                humidity: 0.98,
                pressure: 1016.8,
                windSpeed: 2.59,
                windGust: 4.2,
                windBearing: 121,
                cloudCover: 0,
                uvIndex: 1,
                visibility: 16.093,
                ozone: 270.7
            },
            {
                time: 1574251200,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 5.17,
                apparentTemperature: 2.99,
                dewPoint: 4.62,
                humidity: 0.96,
                pressure: 1016.6,
                windSpeed: 2.63,
                windGust: 4.57,
                windBearing: 126,
                cloudCover: 0,
                uvIndex: 1,
                visibility: 16.093,
                ozone: 270.7
            },
            {
                time: 1574254800,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 5.59,
                apparentTemperature: 3.54,
                dewPoint: 4.77,
                humidity: 0.94,
                pressure: 1016,
                windSpeed: 2.58,
                windGust: 4.46,
                windBearing: 119,
                cloudCover: 0,
                uvIndex: 1,
                visibility: 16.093,
                ozone: 271.3
            },
            {
                time: 1574258400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 5.34,
                apparentTemperature: 3.32,
                dewPoint: 4.53,
                humidity: 0.95,
                pressure: 1015.4,
                windSpeed: 2.48,
                windGust: 4.14,
                windBearing: 117,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 272.3
            },
            {
                time: 1574262000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 4.52,
                apparentTemperature: 2.4,
                dewPoint: 3.56,
                humidity: 0.94,
                pressure: 1015.2,
                windSpeed: 2.42,
                windGust: 4.03,
                windBearing: 118,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 273.8
            },
            {
                time: 1574265600,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0.0089,
                precipProbability: 0.04,
                precipType: 'rain',
                temperature: 4.28,
                apparentTemperature: 2.03,
                dewPoint: 3.16,
                humidity: 0.92,
                pressure: 1014.9,
                windSpeed: 2.51,
                windGust: 4.42,
                windBearing: 119,
                cloudCover: 0.02,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 276.2
            },
            {
                time: 1574269200,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0.0065,
                precipProbability: 0.02,
                precipType: 'rain',
                temperature: 3.67,
                apparentTemperature: 1.19,
                dewPoint: 2.66,
                humidity: 0.93,
                pressure: 1014.8,
                windSpeed: 2.65,
                windGust: 5.03,
                windBearing: 122,
                cloudCover: 0.05,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 279
            },
            {
                time: 1574272800,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                temperature: 3.03,
                apparentTemperature: 0.35,
                dewPoint: 2.36,
                humidity: 0.95,
                pressure: 1014.5,
                windSpeed: 2.75,
                windGust: 5.48,
                windBearing: 116,
                cloudCover: 0.07,
                uvIndex: 0,
                visibility: 16.093,
                ozone: 281.7
            }
        ]
    },
    daily: {
        summary: 'Light rain throughout the week.',
        icon: 'rain',
        data: [
            {
                time: 1574031600,
                summary: 'Light rain throughout the day.',
                icon: 'rain',
                sunriseTime: 1574060880,
                sunsetTime: 1574091960,
                moonPhase: 0.71,
                precipIntensity: 0.1679,
                precipIntensityMax: 0.5601,
                precipIntensityMaxTime: 1574051880,
                precipProbability: 0.95,
                precipType: 'rain',
                temperatureHigh: 8.3,
                temperatureHighTime: 1574083380,
                temperatureLow: 5.71,
                temperatureLowTime: 1574134860,
                apparentTemperatureHigh: 6.62,
                apparentTemperatureHighTime: 1574085660,
                apparentTemperatureLow: 2.11,
                apparentTemperatureLowTime: 1574132340,
                dewPoint: 5.15,
                humidity: 0.91,
                pressure: 1008.8,
                windSpeed: 4.15,
                windGust: 12.54,
                windGustTime: 1574100840,
                windBearing: 327,
                cloudCover: 0.81,
                uvIndex: 1,
                uvIndexTime: 1574076060,
                visibility: 10.087,
                ozone: 326.9,
                temperatureMin: 4.51,
                temperatureMinTime: 1574043660,
                temperatureMax: 8.33,
                temperatureMaxTime: 1574110920,
                apparentTemperatureMin: 1.65,
                apparentTemperatureMinTime: 1574060040,
                apparentTemperatureMax: 6.62,
                apparentTemperatureMaxTime: 1574085660
            },
            {
                time: 1574118000,
                summary: 'Possible light rain in the morning.',
                icon: 'rain',
                sunriseTime: 1574147400,
                sunsetTime: 1574178300,
                moonPhase: 0.75,
                precipIntensity: 0.1741,
                precipIntensityMax: 0.9577,
                precipIntensityMaxTime: 1574132940,
                precipProbability: 0.69,
                precipType: 'rain',
                temperatureHigh: 8.8,
                temperatureHighTime: 1574165520,
                temperatureLow: 0.14,
                temperatureLowTime: 1574224860,
                apparentTemperatureHigh: 7.25,
                apparentTemperatureHighTime: 1574166360,
                apparentTemperatureLow: -1.98,
                apparentTemperatureLowTime: 1574225760,
                dewPoint: 5.02,
                humidity: 0.93,
                pressure: 1015.1,
                windSpeed: 3.06,
                windGust: 11.21,
                windGustTime: 1574122320,
                windBearing: 306,
                cloudCover: 0.67,
                uvIndex: 1,
                uvIndexTime: 1574162820,
                visibility: 16.093,
                ozone: 312,
                temperatureMin: 2.15,
                temperatureMinTime: 1574204400,
                temperatureMax: 8.8,
                temperatureMaxTime: 1574165520,
                apparentTemperatureMin: 2.11,
                apparentTemperatureMinTime: 1574132340,
                apparentTemperatureMax: 7.25,
                apparentTemperatureMaxTime: 1574166360
            },
            {
                time: 1574204400,
                summary: 'Clear throughout the day.',
                icon: 'clear-day',
                sunriseTime: 1574233860,
                sunsetTime: 1574264580,
                moonPhase: 0.78,
                precipIntensity: 0.0057,
                precipIntensityMax: 0.017,
                precipIntensityMaxTime: 1574236680,
                precipProbability: 0.12,
                precipType: 'rain',
                temperatureHigh: 5.88,
                temperatureHighTime: 1574255220,
                temperatureLow: 0.06,
                temperatureLowTime: 1574315640,
                apparentTemperatureHigh: 3.55,
                apparentTemperatureHighTime: 1574255520,
                apparentTemperatureLow: -3.98,
                apparentTemperatureLowTime: 1574315760,
                dewPoint: 2.35,
                humidity: 0.98,
                pressure: 1016.4,
                windSpeed: 2.33,
                windGust: 5.66,
                windGustTime: 1574278380,
                windBearing: 129,
                cloudCover: 0.15,
                uvIndex: 1,
                uvIndexTime: 1574249100,
                visibility: 15.943,
                ozone: 278.1,
                temperatureMin: 0.14,
                temperatureMinTime: 1574224860,
                temperatureMax: 5.88,
                temperatureMaxTime: 1574255220,
                apparentTemperatureMin: -1.98,
                apparentTemperatureMinTime: 1574225760,
                apparentTemperatureMax: 3.55,
                apparentTemperatureMaxTime: 1574255520
            },
            {
                time: 1574290800,
                summary: 'Mostly cloudy throughout the day.',
                icon: 'partly-cloudy-day',
                sunriseTime: 1574320380,
                sunsetTime: 1574350920,
                moonPhase: 0.82,
                precipIntensity: 0.0045,
                precipIntensityMax: 0.0136,
                precipIntensityMaxTime: 1574290800,
                precipProbability: 0.08,
                precipType: 'rain',
                temperatureHigh: 7.92,
                temperatureHighTime: 1574343840,
                temperatureLow: 3.53,
                temperatureLowTime: 1574402280,
                apparentTemperatureHigh: 4.96,
                apparentTemperatureHighTime: 1574344020,
                apparentTemperatureLow: 0.12,
                apparentTemperatureLowTime: 1574402220,
                dewPoint: 2.73,
                humidity: 0.93,
                pressure: 1010.2,
                windSpeed: 4.17,
                windGust: 10.93,
                windGustTime: 1574370660,
                windBearing: 136,
                cloudCover: 0.61,
                uvIndex: 1,
                uvIndexTime: 1574335560,
                visibility: 15.025,
                ozone: 302.9,
                temperatureMin: 0.06,
                temperatureMinTime: 1574315640,
                temperatureMax: 7.92,
                temperatureMaxTime: 1574343840,
                apparentTemperatureMin: -3.98,
                apparentTemperatureMinTime: 1574315760,
                apparentTemperatureMax: 4.96,
                apparentTemperatureMaxTime: 1574344020
            },
            {
                time: 1574377200,
                summary: 'Overcast throughout the day.',
                icon: 'cloudy',
                sunriseTime: 1574406900,
                sunsetTime: 1574437260,
                moonPhase: 0.86,
                precipIntensity: 0.016,
                precipIntensityMax: 0.0688,
                precipIntensityMaxTime: 1574395320,
                precipProbability: 0.34,
                precipType: 'rain',
                temperatureHigh: 9.95,
                temperatureHighTime: 1574428980,
                temperatureLow: 5.59,
                temperatureLowTime: 1574478000,
                apparentTemperatureHigh: 7.69,
                apparentTemperatureHighTime: 1574429340,
                apparentTemperatureLow: 2.01,
                apparentTemperatureLowTime: 1574478000,
                dewPoint: 6.24,
                humidity: 0.96,
                pressure: 1007.6,
                windSpeed: 4.4,
                windGust: 12.8,
                windGustTime: 1574463600,
                windBearing: 146,
                cloudCover: 0.97,
                uvIndex: 1,
                uvIndexTime: 1574421900,
                visibility: 16.093,
                ozone: 296.5,
                temperatureMin: 3.53,
                temperatureMinTime: 1574402280,
                temperatureMax: 9.95,
                temperatureMaxTime: 1574428980,
                apparentTemperatureMin: 0.12,
                apparentTemperatureMinTime: 1574402220,
                apparentTemperatureMax: 7.69,
                apparentTemperatureMaxTime: 1574429340
            },
            {
                time: 1574463600,
                summary: 'Mostly cloudy throughout the day.',
                icon: 'partly-cloudy-day',
                sunriseTime: 1574493420,
                sunsetTime: 1574523600,
                moonPhase: 0.9,
                precipIntensity: 0.0149,
                precipIntensityMax: 0.0872,
                precipIntensityMaxTime: 1574488920,
                precipProbability: 0.29,
                precipType: 'rain',
                temperatureHigh: 11.66,
                temperatureHighTime: 1574513940,
                temperatureLow: 5.02,
                temperatureLowTime: 1574575140,
                apparentTemperatureHigh: 11.38,
                apparentTemperatureHighTime: 1574513940,
                apparentTemperatureLow: 3.09,
                apparentTemperatureLowTime: 1574575200,
                dewPoint: 7.24,
                humidity: 0.95,
                pressure: 1004,
                windSpeed: 4.58,
                windGust: 13.31,
                windGustTime: 1574468400,
                windBearing: 124,
                cloudCover: 0.93,
                uvIndex: 1,
                uvIndexTime: 1574508360,
                visibility: 16.093,
                ozone: 301.5,
                temperatureMin: 5.59,
                temperatureMinTime: 1574478000,
                temperatureMax: 11.66,
                temperatureMaxTime: 1574513940,
                apparentTemperatureMin: 2.01,
                apparentTemperatureMinTime: 1574478000,
                apparentTemperatureMax: 11.38,
                apparentTemperatureMaxTime: 1574513940
            },
            {
                time: 1574550000,
                summary: 'Light rain overnight.',
                icon: 'rain',
                sunriseTime: 1574579880,
                sunsetTime: 1574609940,
                moonPhase: 0.93,
                precipIntensity: 0.0396,
                precipIntensityMax: 0.4246,
                precipIntensityMaxTime: 1574636280,
                precipProbability: 0.57,
                precipType: 'rain',
                temperatureHigh: 10.74,
                temperatureHighTime: 1574607240,
                temperatureLow: 8.1,
                temperatureLowTime: 1574650800,
                apparentTemperatureHigh: 10.61,
                apparentTemperatureHighTime: 1574606700,
                apparentTemperatureLow: 5.36,
                apparentTemperatureLowTime: 1574662080,
                dewPoint: 8.23,
                humidity: 1,
                pressure: 1007.1,
                windSpeed: 4.24,
                windGust: 12.05,
                windGustTime: 1574636400,
                windBearing: 175,
                cloudCover: 0.66,
                uvIndex: 1,
                uvIndexTime: 1574594760,
                visibility: 16.093,
                ozone: 268.6,
                temperatureMin: 5.02,
                temperatureMinTime: 1574575140,
                temperatureMax: 10.74,
                temperatureMaxTime: 1574607240,
                apparentTemperatureMin: 3.09,
                apparentTemperatureMinTime: 1574575200,
                apparentTemperatureMax: 10.61,
                apparentTemperatureMaxTime: 1574606700
            },
            {
                time: 1574636400,
                summary: 'Light rain throughout the day.',
                icon: 'rain',
                sunriseTime: 1574666400,
                sunsetTime: 1574696280,
                moonPhase: 0.97,
                precipIntensity: 0.2636,
                precipIntensityMax: 1.125,
                precipIntensityMaxTime: 1574693940,
                precipProbability: 1,
                precipType: 'rain',
                temperatureHigh: 10.67,
                temperatureHighTime: 1574704560,
                temperatureLow: 7.26,
                temperatureLowTime: 1574732280,
                apparentTemperatureHigh: 10.68,
                apparentTemperatureHighTime: 1574703480,
                apparentTemperatureLow: 4.15,
                apparentTemperatureLowTime: 1574731920,
                dewPoint: 9.67,
                humidity: 1,
                pressure: 1004.3,
                windSpeed: 6.36,
                windGust: 14.41,
                windGustTime: 1574717700,
                windBearing: 199,
                cloudCover: 1,
                uvIndex: 1,
                uvIndexTime: 1574681160,
                visibility: 15.881,
                ozone: 247,
                temperatureMin: 8.1,
                temperatureMinTime: 1574650800,
                temperatureMax: 10.97,
                temperatureMaxTime: 1574655840,
                apparentTemperatureMin: 5.24,
                apparentTemperatureMinTime: 1574721840,
                apparentTemperatureMax: 11.03,
                apparentTemperatureMaxTime: 1574656080
            }
        ]
    },
    flags: {
        sources: [
            'meteoalarm',
            'cmc',
            'gfs',
            'icon',
            'isd',
            'madis'
        ],
        'nearest-station': 2.981,
        units: 'si'
    },
    offset: 1
};
